# Generated by Django 4.2.3 on 2023-09-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='yangilik_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=111)),
                ('video', models.FileField(null=True, upload_to='yangi/fayllar', verbose_name='')),
                ('comentlarsoni', models.IntegerField()),
                ('views', models.IntegerField(default=0)),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
        migrations.CreateModel(
            name='yangilikDetel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('rasm', models.ImageField(upload_to='news/images')),
                ('rasm1', models.ImageField(upload_to='news/images')),
                ('rasm2', models.ImageField(upload_to='news/images')),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=250)),
                ('kontent', models.TextField()),
                ('rasm', models.ImageField(upload_to='news/images')),
                ('filelar', models.FileField(upload_to='news/fayllar')),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilganVaqti', models.DateTimeField(auto_now_add=True)),
                ('ozgarishVaqti', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('QR', 'qoralama'), ('CHP', 'chopetilish')], default='QR', max_length=3)),
                ('views', models.IntegerField(default=0)),
                ('comentlarsoni', models.IntegerField()),
                ('qaynoq_yangiliklar', models.BooleanField(default=False)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
