# Generated by Django 4.2.3 on 2023-09-13 19:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_songiyangiliklar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songiyangiliklar',
            name='nom',
            field=models.CharField(max_length=10001),
        ),
        migrations.AlterField(
            model_name='songiyangiliklar',
            name='slug',
            field=models.SlugField(max_length=10001),
        ),
        migrations.CreateModel(
            name='Voqealar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10001)),
                ('slug', models.SlugField(max_length=10001)),
                ('kontent', models.TextField()),
                ('video', models.FileField(upload_to='yangi/fayllar')),
                ('rasm', models.ImageField(upload_to='news/images')),
                ('chopetilishVaqti', models.DateTimeField(default=django.utils.timezone.now)),
                ('yaratilganVaqti', models.DateTimeField(auto_now_add=True)),
                ('ozgarishVaqti', models.DateTimeField(auto_now=True)),
                ('holati', models.CharField(choices=[('QR', 'qoralama'), ('CHP', 'chopetilish')], default='QR', max_length=3)),
                ('views', models.IntegerField(default=0)),
                ('kategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category')),
            ],
            options={
                'ordering': ['-chopetilishVaqti'],
            },
        ),
    ]
