# Generated by Django 4.2.3 on 2023-09-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_songiyangiliklar_nom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='news',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.RemoveField(
            model_name='news',
            name='kategory',
        ),
        migrations.DeleteModel(
            name='yangilik_video',
        ),
        migrations.DeleteModel(
            name='yangilikDetel',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
